// flow-typed signature: 28e37d03eb1c56f0e950484c0f630262
// flow-typed version: <<STUB>>/babel-plugin-transform-strict-mode_v^6.24.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-strict-mode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-strict-mode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-strict-mode/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-strict-mode/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-strict-mode/lib/index'>;
}
