// flow-typed signature: 320c6adc31e32b0286005cc8443d85c7
// flow-typed version: <<STUB>>/firebase-key_v^1.0.4/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-key'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-key' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-key/bundles/firebase-key.min.umd' {
  declare module.exports: any;
}

declare module 'firebase-key/bundles/firebase-key.umd' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/index' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-alphabet' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-date' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-decode-lexicographic' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-decode' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-decrement' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-encode-lexicographic' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-encode' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-increment' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-key' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key-milliseconds' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/key' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/text-random-string' {
  declare module.exports: any;
}

declare module 'firebase-key/dist/text-repeat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-key/bundles/firebase-key.min.umd.js' {
  declare module.exports: $Exports<'firebase-key/bundles/firebase-key.min.umd'>;
}
declare module 'firebase-key/bundles/firebase-key.umd.js' {
  declare module.exports: $Exports<'firebase-key/bundles/firebase-key.umd'>;
}
declare module 'firebase-key/dist/index.js' {
  declare module.exports: $Exports<'firebase-key/dist/index'>;
}
declare module 'firebase-key/dist/key-alphabet.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-alphabet'>;
}
declare module 'firebase-key/dist/key-date.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-date'>;
}
declare module 'firebase-key/dist/key-decode-lexicographic.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-decode-lexicographic'>;
}
declare module 'firebase-key/dist/key-decode.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-decode'>;
}
declare module 'firebase-key/dist/key-decrement.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-decrement'>;
}
declare module 'firebase-key/dist/key-encode-lexicographic.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-encode-lexicographic'>;
}
declare module 'firebase-key/dist/key-encode.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-encode'>;
}
declare module 'firebase-key/dist/key-increment.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-increment'>;
}
declare module 'firebase-key/dist/key-key.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-key'>;
}
declare module 'firebase-key/dist/key-milliseconds.js' {
  declare module.exports: $Exports<'firebase-key/dist/key-milliseconds'>;
}
declare module 'firebase-key/dist/key.js' {
  declare module.exports: $Exports<'firebase-key/dist/key'>;
}
declare module 'firebase-key/dist/text-random-string.js' {
  declare module.exports: $Exports<'firebase-key/dist/text-random-string'>;
}
declare module 'firebase-key/dist/text-repeat.js' {
  declare module.exports: $Exports<'firebase-key/dist/text-repeat'>;
}
